import json
import random
import sys

import requests
from bs4 import BeautifulSoup
from lxml import etree

shop = "https://scandinaviangifts.com/tvars-030/"
run_function = lambda x, y: x if y in x else x + [y]


def div_list(listTemp, seg=5):
    res = []
    for j in range(seg):
        res.append([i for i in range(0 + j, len(listTemp), len(listTemp) // seg + 1)])
    return res


def get_gift_page(http="https://scandinaviangifts.com/candy-and-treats/"):
    response = str(requests.get(http).text)
    html = etree.HTML(response)  # 初始化生成一个XPath解析对象
    soup = BeautifulSoup(response, 'html.parser')

    urls = [i.a["href"] for i in soup.find_all("h4", class_="card-title")]
    # print(urls)
    return urls


def get_info(url):
    def random_discount(p):
        s = 100
        if random.random() > 0.7:
            s = random.randint(20, 99)
            p = p * s / 100
        return s, p

    def random_size_sale():
        each_sales = []
        each_income = []
        for i in range(len(size)):
            each_sales.append(random.randint(0, sales - sum(each_sales)))
        each_income = [round(sum([random_discount(price)[1] for j in range(i)]), 2) for i in each_sales]
        return each_sales, each_income

    response = str(requests.get(url).text)
    html = etree.HTML(response)
    soup = BeautifulSoup(response, 'html.parser')
    title = html.xpath('//html/body/div[7]/div[1]/div/div[1]/section[1]/div/h1/text()')[0]
    price = eval(html.xpath('//html/body/div[7]/div[1]/div/div[1]/section[1]/div/div[4]/div/span/text()')[0][1:])
    img = soup.find_all("figure", class_="productView-image")[0].a['href']
    size = [i.get_text() for i in soup.find_all("span", class_="form-option-variant")]
    size = ["normal"] if len(size) == 0 else size
    des = soup.find_all("div", class_="tab-content is-active")[0].get_text()
    # print(title, price, img, size, des)
    dis_state, dis_price = random_discount(price)
    sales = random.randint(0, 999)
    size_sales, size_income = random_size_sale()
    income = round(sum([random_discount(price)[1] for i in range(sales)]), 2)
    size_stock = [random.randint(0, 999) for i in range(len(size))]
    return {
        "gift_name": title,
        "gift_price": price,
        "gift_discount_price": dis_price,
        "gift_discount_state": str(dis_state) + "%",
        "gift_description": des,
        "gift_category": "",
        "gift_side_category1": "",
        "gift_side_category2": "",
        "gift_cover_url": img,
        "gift_show_url1": "",
        "gift_show_url2": "",
        "gift_show_url3": "",
        "gift_show_url4": "",
        "gift_sales": sales,
        "gift_income": income,
        "gift_size": [{"size": size[i],
                       "stock": size_stock[i],
                       "this_size_sales": size_sales[i],
                       "this_size_income": size_income[i]} for i in range(len(size))]

    }


def get_url(shop, count=200):
    response = str(requests.get(shop).text)
    soup = BeautifulSoup(response, 'html.parser')
    https = [i["href"] for i in soup.find_all("a", class_="navPage-subMenu-action navPages-action")]
    res = []
    urls = []
    print(https)
    for http in https:
        # print(urls)
        urls += get_gift_page(http)
        # if count != -1 and len(urls) > count:
        #     return urls
    return urls


def foo(s_u):
    f = open('giftlist.json', 'a', encoding="utf-8")

    sys.stdout = f
    for u in s_u:
        res = get_info(u)
        print(json.dumps(res), ",")


# pprint.pprint(res)


if __name__ == '__main__':
    # if os.path.exists("giftlist.json"):
    #     os.remove("giftlist.json")
    #
    # urls = get_url(shop)
    # seg_urls = list(div_list(urls))
    # pprint.pprint(seg_urls)
    # with Pool(5) as p:
    #     p.map(foo, seg_urls)
    print(div_list(['https://scandinaviangifts.com/utvaer-mens-windbreaker-vest/',
                    'https://scandinaviangifts.com/utvaer-womens-windbreaker-vest/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-mens-vest/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-womens-vest/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-mens-jacket/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-womens-jacket/',
                    'https://scandinaviangifts.com/firda-quilted-jacket/',
                    'https://scandinaviangifts.com/olympia-kids-sweater/',
                    'https://scandinaviangifts.com/winterland-kids-sweater/',
                    'https://scandinaviangifts.com/vilja-weatherproof-hoodie/',
                    'https://scandinaviangifts.com/vegard-weatherproof-hoodie/',
                    'https://scandinaviangifts.com/alvoy-quilted-jacket/',
                    'https://scandinaviangifts.com/winterland-mens-sweater/',
                    'https://scandinaviangifts.com/winterland-womens-sweater/',
                    'https://scandinaviangifts.com/winter-star-mens-sweater/',
                    'https://scandinaviangifts.com/winter-star-womens-sweater/',
                    'https://scandinaviangifts.com/bjornoy-mens-sweater/',
                    'https://scandinaviangifts.com/vagsoy-mens-sweater/',
                    'https://scandinaviangifts.com/moritz-mens-sweater/',
                    'https://scandinaviangifts.com/geilo-mens-sweater/',
                    'https://scandinaviangifts.com/lahti-mens-sweater/',
                    'https://scandinaviangifts.com/veskre-weatherproof-mens-sweater/',
                    'https://scandinaviangifts.com/mount-ashcroft-mens-sweater/',
                    'https://scandinaviangifts.com/history-unisex-sweater/',
                    'https://scandinaviangifts.com/spirit-mens-jacket/',
                    'https://scandinaviangifts.com/spirit-mens-sweater/',
                    'https://scandinaviangifts.com/history-mens-pants/',
                    'https://scandinaviangifts.com/history-basic-mens-sweater/',
                    'https://scandinaviangifts.com/spirit-mens-pants/',
                    'https://scandinaviangifts.com/spirit-basic-mens-sweater/',
                    'https://scandinaviangifts.com/veskre-weatherproof-womens-sweater/',
                    'https://scandinaviangifts.com/hoven-mens-sweater/',
                    'https://scandinaviangifts.com/hoven-womens-sweater/',
                    'https://scandinaviangifts.com/firda-womens-sweater/',
                    'https://scandinaviangifts.com/mount-ashcroft-womens-sweater/',
                    'https://scandinaviangifts.com/mount-red-womens-sweater/',
                    'https://scandinaviangifts.com/vegard-mens-jacket/',
                    'https://scandinaviangifts.com/vegard-mens-sweater/',
                    'https://scandinaviangifts.com/alvoy-mens-sweater/',
                    'https://scandinaviangifts.com/vilja-womens-jacket/',
                    'https://scandinaviangifts.com/vilja-womens-sweater/',
                    'https://scandinaviangifts.com/falun-heron-womens-sweater/',
                    'https://scandinaviangifts.com/tyssoy-mens-sweater/',
                    'https://scandinaviangifts.com/bjoroy-womens-sweater/',
                    'https://scandinaviangifts.com/falun-womens-sweater/',
                    'https://scandinaviangifts.com/myking-mens-sweater/',
                    'https://scandinaviangifts.com/myking-womens-sweater/',
                    'https://scandinaviangifts.com/hodur-mens-sweater/',
                    'https://scandinaviangifts.com/sigurd-mens-sweater/',
                    'https://scandinaviangifts.com/vegvisir-mens-sweater/',
                    'https://scandinaviangifts.com/kvitseid-womens-jacket/',
                    'https://scandinaviangifts.com/kvinesdal-womens-jacket/',
                    'https://scandinaviangifts.com/brimse-womens-jacket/', 'https://scandinaviangifts.com/freja-cape/',
                    'https://scandinaviangifts.com/fongen-weatherproof-womens-sweater/',
                    'https://scandinaviangifts.com/vail-weatherproof-mens-sweater/',
                    'https://scandinaviangifts.com/fongen-weatherproof-mens-sweater/',
                    'https://scandinaviangifts.com/ingeborg-womens-jacket/',
                    'https://scandinaviangifts.com/140th-anniversary-womens-jacket/',
                    'https://scandinaviangifts.com/140th-anniversary-mens-sweater/',
                    'https://scandinaviangifts.com/rose-shawl/', 'https://scandinaviangifts.com/vail-unisex-sweater/',
                    'https://scandinaviangifts.com/christiania-womens-jacket/',
                    'https://scandinaviangifts.com/peace-womens-sweater/',
                    'https://scandinaviangifts.com/setesdal-unisex-sweater/',
                    'https://scandinaviangifts.com/olympia-kids-sweater/',
                    'https://scandinaviangifts.com/winterland-kids-sweater/',
                    'https://scandinaviangifts.com/moritz-mens-sweater/',
                    'https://scandinaviangifts.com/spirit-kids-sweater/',
                    'https://scandinaviangifts.com/spirit-mens-sweater/',
                    'https://scandinaviangifts.com/spirit-womens-sweater/',
                    'https://scandinaviangifts.com/wergeland-kids-jacket/',
                    'https://scandinaviangifts.com/moritz-kids-sweater/',
                    'https://scandinaviangifts.com/moritz-womens-sweater/',
                    'https://scandinaviangifts.com/cortina-unisex-sweater/',
                    'https://scandinaviangifts.com/cortina-kids-sweater/',
                    'https://scandinaviangifts.com/norway-kids-headband/',
                    'https://scandinaviangifts.com/spirit-kids-hat/',
                    'https://scandinaviangifts.com/cortina-kids-hat-4-8-years/',
                    'https://scandinaviangifts.com/cortina-kids-hat-2-4-years/',
                    'https://scandinaviangifts.com/winterland-kids-hat/',
                    'https://scandinaviangifts.com/olympia-kids-hat/', 'https://scandinaviangifts.com/maloy-hat/',
                    'https://scandinaviangifts.com/vilja-mittens/', 'https://scandinaviangifts.com/moritz-mittens/',
                    'https://scandinaviangifts.com/falun-mittens/', 'https://scandinaviangifts.com/dystingen-headband/',
                    'https://scandinaviangifts.com/vilja-hat/', 'https://scandinaviangifts.com/winterland-hat/',
                    'https://scandinaviangifts.com/winter-star-hat/', 'https://scandinaviangifts.com/olympia-headband/',
                    'https://scandinaviangifts.com/dystingen-hat/', 'https://scandinaviangifts.com/1879-hat/',
                    'https://scandinaviangifts.com/mount-olympus-hat/',
                    'https://scandinaviangifts.com/team-norway-hat/', 'https://scandinaviangifts.com/olympia-hat/',
                    'https://scandinaviangifts.com/bjoroy-hat/', 'https://scandinaviangifts.com/norway-kids-headband/',
                    'https://scandinaviangifts.com/moritz-mens-sweater/',
                    'https://scandinaviangifts.com/geilo-mens-sweater/',
                    'https://scandinaviangifts.com/hodur-mens-sweater/',
                    'https://scandinaviangifts.com/sigurd-mens-sweater/',
                    'https://scandinaviangifts.com/vegvisir-mens-sweater/',
                    'https://scandinaviangifts.com/vegard-mens-jacket/',
                    'https://scandinaviangifts.com/vegard-mens-sweater/',
                    'https://scandinaviangifts.com/alvoy-mens-sweater/',
                    'https://scandinaviangifts.com/lahti-mens-sweater/',
                    'https://scandinaviangifts.com/veskre-weatherproof-mens-sweater/',
                    'https://scandinaviangifts.com/mount-ashcroft-mens-sweater/',
                    'https://scandinaviangifts.com/history-unisex-sweater/',
                    'https://scandinaviangifts.com/spirit-mens-jacket/',
                    'https://scandinaviangifts.com/spirit-mens-sweater/',
                    'https://scandinaviangifts.com/history-mens-pants/',
                    'https://scandinaviangifts.com/history-basic-mens-sweater/',
                    'https://scandinaviangifts.com/spirit-mens-pants/',
                    'https://scandinaviangifts.com/spirit-basic-mens-sweater/',
                    'https://scandinaviangifts.com/kvitseid-womens-jacket/',
                    'https://scandinaviangifts.com/kvinesdal-womens-jacket/',
                    'https://scandinaviangifts.com/vilja-womens-jacket/',
                    'https://scandinaviangifts.com/vilja-womens-sweater/',
                    'https://scandinaviangifts.com/falun-heron-womens-sweater/',
                    'https://scandinaviangifts.com/veskre-weatherproof-womens-sweater/',
                    'https://scandinaviangifts.com/hoven-womens-sweater/',
                    'https://scandinaviangifts.com/firda-womens-sweater/',
                    'https://scandinaviangifts.com/mount-ashcroft-womens-sweater/',
                    'https://scandinaviangifts.com/mount-red-womens-sweater/',
                    'https://scandinaviangifts.com/spirit-womens-jacket/',
                    'https://scandinaviangifts.com/stargaze-womens-leggings/',
                    'https://scandinaviangifts.com/spirit-leggings/',
                    'https://scandinaviangifts.com/stargaze-basic-womens-sweater/',
                    'https://scandinaviangifts.com/spirit-womens-sweater/',
                    'https://scandinaviangifts.com/spirit-basic-womens-sweater/',
                    'https://scandinaviangifts.com/brimse-womens-jacket/',
                    'https://scandinaviangifts.com/bjoroy-womens-sweater/',
                    'https://scandinaviangifts.com/utvaer-mens-windbreaker-vest/',
                    'https://scandinaviangifts.com/utvaer-womens-windbreaker-vest/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-mens-vest/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-womens-vest/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-mens-jacket/',
                    'https://scandinaviangifts.com/veoy-pile-fleece-womens-jacket/',
                    'https://scandinaviangifts.com/firda-quilted-jacket/',
                    'https://scandinaviangifts.com/vilja-weatherproof-hoodie/',
                    'https://scandinaviangifts.com/vegard-weatherproof-hoodie/',
                    'https://scandinaviangifts.com/alvoy-quilted-jacket/',
                    'https://scandinaviangifts.com/winterland-mens-sweater/',
                    'https://scandinaviangifts.com/winterland-womens-sweater/',
                    'https://scandinaviangifts.com/winter-star-mens-sweater/',
                    'https://scandinaviangifts.com/winter-star-womens-sweater/',
                    'https://scandinaviangifts.com/bjornoy-mens-sweater/',
                    'https://scandinaviangifts.com/vagsoy-mens-sweater/',
                    'https://scandinaviangifts.com/maloy-mens-sweater/',
                    'https://scandinaviangifts.com/valloy-mens-sweater/',
                    'https://scandinaviangifts.com/tyssoy-mens-sweater-sale/',
                    'https://scandinaviangifts.com/ekelund-pillow-insert-duck-feather/',
                    'https://scandinaviangifts.com/gasoga-080/', 'https://scandinaviangifts.com/gasoga-091/',
                    'https://scandinaviangifts.com/ruta/', 'https://scandinaviangifts.com/block-091/',
                    'https://scandinaviangifts.com/block-080/', 'https://scandinaviangifts.com/diska/',
                    'https://scandinaviangifts.com/gasoga-000/', 'https://scandinaviangifts.com/gasoga-070/',
                    'https://scandinaviangifts.com/tvarrand/', 'https://scandinaviangifts.com/unicorn/',
                    'https://scandinaviangifts.com/new-arrival/', 'https://scandinaviangifts.com/friends/',
                    'https://scandinaviangifts.com/baby-dino/', 'https://scandinaviangifts.com/dinosaurius/',
                    'https://scandinaviangifts.com/chameleon/', 'https://scandinaviangifts.com/night-time/',
                    'https://scandinaviangifts.com/day-time/', 'https://scandinaviangifts.com/gasoga-080/',
                    'https://scandinaviangifts.com/gasoga-091/', 'https://scandinaviangifts.com/ruta/',
                    'https://scandinaviangifts.com/block-091/', 'https://scandinaviangifts.com/block-080/',
                    'https://scandinaviangifts.com/krasse/', 'https://scandinaviangifts.com/summerfield/',
                    'https://scandinaviangifts.com/tvars-090/', 'https://scandinaviangifts.com/tvars-080/',
                    'https://scandinaviangifts.com/tvars-030/', 'https://scandinaviangifts.com/elsa/',
                    'https://scandinaviangifts.com/daffodil/', 'https://scandinaviangifts.com/soft/',
                    'https://scandinaviangifts.com/kust/', 'https://scandinaviangifts.com/glassar/',
                    'https://scandinaviangifts.com/sticky-stripe/', 'https://scandinaviangifts.com/rander/',
                    'https://scandinaviangifts.com/wood/', 'https://scandinaviangifts.com/springtime-gnome-notes/',
                    'https://scandinaviangifts.com/the-little-springtime-book-of-gnomes/',
                    'https://scandinaviangifts.com/relaxed-rustic-bring-scandinavian-tranquility-nature-into-your-home/',
                    'https://scandinaviangifts.com/for-the-love-of-cod/',
                    'https://scandinaviangifts.com/hygge-the-danish-art-of-happiness/',
                    'https://scandinaviangifts.com/nordicana-100-icons-of-scandi-culture/',
                    'https://scandinaviangifts.com/nordic-theory-of-everything-in-search-of-a-better-life/',
                    'https://scandinaviangifts.com/little-book-of-hygge-danish-secrets-to-happy-living/',
                    'https://scandinaviangifts.com/joy-of-hygge/',
                    'https://scandinaviangifts.com/skandikitchen-fika-hygge/',
                    'https://scandinaviangifts.com/how-to-hygge/', 'https://scandinaviangifts.com/the-christmas-wish/',
                    'https://scandinaviangifts.com/little-tomtes-christmas-wish/',
                    'https://scandinaviangifts.com/keeping-christmas/',
                    'https://scandinaviangifts.com/the-polar-bear-wish/',
                    'https://scandinaviangifts.com/the-reindeer-wish/',
                    'https://scandinaviangifts.com/nordic-coloring-book/',
                    'https://scandinaviangifts.com/2022-calendar-denmark/',
                    'https://scandinaviangifts.com/2022-calendar-finland/',
                    'https://scandinaviangifts.com/swedish-fika/',
                    'https://scandinaviangifts.com/modern-scandinavian-baking/',
                    'https://scandinaviangifts.com/smorgasbord-recipes-book/',
                    'https://scandinaviangifts.com/bronte-at-home/',
                    'https://scandinaviangifts.com/scandinavian-gatherings/',
                    'https://scandinaviangifts.com/classic-recipes-of-norway/',
                    'https://scandinaviangifts.com/classic-recipes-of-denmark/',
                    'https://scandinaviangifts.com/classic-recipes-of-finland/',
                    'https://scandinaviangifts.com/classic-recipes-of-sweden/',
                    'https://scandinaviangifts.com/the-nordic-kitchen/',
                    'https://scandinaviangifts.com/ebelskivers-cookbook/',
                    'https://scandinaviangifts.com/scandinavian-comfort-food/',
                    'https://scandinaviangifts.com/swedish-cakes-cookies/',
                    'https://scandinaviangifts.com/notes-from-a-swedish-kitchen/',
                    'https://scandinaviangifts.com/finnish-touches/',
                    'https://scandinaviangifts.com/norwegian-touches/',
                    'https://scandinaviangifts.com/scandinavian-cooking/',
                    'https://scandinaviangifts.com/swedish-touches/',
                    'https://scandinaviangifts.com/the-emigrant-novels/',
                    'https://scandinaviangifts.com/the-ice-princess/',
                    'https://scandinaviangifts.com/norwegian-troll-tales/',
                    'https://scandinaviangifts.com/the-norse-myths/',
                    'https://scandinaviangifts.com/daulaires-book-of-trolls/',
                    'https://scandinaviangifts.com/book-of-viking-myths/',
                    'https://scandinaviangifts.com/norse-mythology/',
                    'https://scandinaviangifts.com/adventures-of-thor-the-thunder-god/',
                    'https://scandinaviangifts.com/daulaires-book-of-norse-myths/',
                    'https://scandinaviangifts.com/children-of-the-northlights/',
                    'https://scandinaviangifts.com/the-12th-man/', 'https://scandinaviangifts.com/report-from-24/',
                    'https://scandinaviangifts.com/abercrombie-trail/', 'https://scandinaviangifts.com/pomme-de-terre/',
                    'https://scandinaviangifts.com/the-sledge-patrol/',
                    'https://scandinaviangifts.com/the-shetland-bus/',
                    'https://scandinaviangifts.com/skis-against-the-atom/',
                    'https://scandinaviangifts.com/we-die-alone/',
                    'https://scandinaviangifts.com/ole-lena-jokes-book-2/',
                    'https://scandinaviangifts.com/ole-lena-jokes-book-1/',
                    'https://scandinaviangifts.com/nordicana-100-icons-of-scandi-culture/',
                    'https://scandinaviangifts.com/nordic-theory-of-everything-in-search-of-a-better-life/',
                    'https://scandinaviangifts.com/little-book-of-hygge-danish-secrets-to-happy-living/',
                    'https://scandinaviangifts.com/laughing-with-lutherans/',
                    'https://scandinaviangifts.com/in-cod-we-trust/',
                    'https://scandinaviangifts.com/vikings-in-the-attic/',
                    'https://scandinaviangifts.com/the-100-year-old-man-who-climbed-out-the-window-disappeared/',
                    'https://scandinaviangifts.com/joy-of-hygge/',
                    'https://scandinaviangifts.com/skandikitchen-fika-hygge/',
                    'https://scandinaviangifts.com/how-to-hygge/',
                    'https://scandinaviangifts.com/almost-nearly-perfect-people-behind-the-myth-of-the-scandinavian-utopia/',
                    'https://scandinaviangifts.com/norwegian-wood/',
                    'https://scandinaviangifts.com/the-last-word-on-lutefisk/',
                    'https://scandinaviangifts.com/the-last-word-on-lefse/',
                    'https://scandinaviangifts.com/insight-travel-guide-finland/',
                    'https://scandinaviangifts.com/insight-travel-guide-norway/',
                    'https://scandinaviangifts.com/the-nordic-book-of-runes/',
                    'https://scandinaviangifts.com/norse-mythology-for-kids/',
                    'https://scandinaviangifts.com/the-viking-hondbok/',
                    'https://scandinaviangifts.com/the-three-vikings/',
                    'https://scandinaviangifts.com/the-viking-warrior/',
                    'https://scandinaviangifts.com/the-world-of-vikings/',
                    'https://scandinaviangifts.com/the-vikings-a-history/',
                    'https://scandinaviangifts.com/far-traveler-voyages-of-a-viking-woman/',
                    'https://scandinaviangifts.com/the-viking-codex/', 'https://scandinaviangifts.com/viking-myths/',
                    'https://scandinaviangifts.com/leif-the-lucky/',
                    'https://scandinaviangifts.com/vikings-raiders-traders-and-masters-of-the-sea/',
                    'https://scandinaviangifts.com/oxford-illustrated-history-of-the-vikings/',
                    'https://scandinaviangifts.com/viking-world-age-of-seafarers-sagas/',
                    'https://scandinaviangifts.com/vikings-the-north-atlantic-saga/',
                    'https://scandinaviangifts.com/beaudin-riley-backpack-brindle-cowhide/',
                    'https://scandinaviangifts.com/copy-of-ozone-mona-linen-socks/',
                    'https://scandinaviangifts.com/rock-snowflake-socks/',
                    'https://scandinaviangifts.com/ozone-floral-ribbons-socks/',
                    'https://scandinaviangifts.com/moomin-sock-pink-stripe/',
                    'https://scandinaviangifts.com/topaz-sneaker/',
                    'https://scandinaviangifts.com/kids-uff-da-baseball-tshirt/',
                    'https://scandinaviangifts.com/buff-rosemaling-multifunctional-headwear-mask/',
                    'https://scandinaviangifts.com/topaz-reindeer-insoles/',
                    'https://scandinaviangifts.com/topaz-boot-oslo-spot/',
                    'https://scandinaviangifts.com/topaz-slipper-ulefoss/',
                    'https://scandinaviangifts.com/ozone-folklore-socks/',
                    'https://scandinaviangifts.com/tshirt-i-wonder-if-lefse-thinks-about-me-too/',
                    'https://scandinaviangifts.com/marius-wool-socks/',
                    'https://scandinaviangifts.com/ozone-dala-horse-socks/',
                    'https://scandinaviangifts.com/norway-flag-jersey/',
                    'https://scandinaviangifts.com/norway-flag-jersey-kids/',
                    'https://scandinaviangifts.com/hooded-flag-jacket/', 'https://scandinaviangifts.com/sigrid-apron/',
                    'https://scandinaviangifts.com/arhus-granate/', 'https://scandinaviangifts.com/arhus-black/',
                    'https://scandinaviangifts.com/arhus-nut/',
                    'https://scandinaviangifts.com/scandinavian-explorer-raincoat-lady/',
                    'https://scandinaviangifts.com/softshell-unisex-jacket-black/',
                    'https://scandinaviangifts.com/softshell-unisex-jacket-blue/',
                    'https://scandinaviangifts.com/softshell-unisex-jacket-red/',
                    'https://scandinaviangifts.com/scandinavian-explorer-sport-bag/',
                    'https://scandinaviangifts.com/raphael-clog/', 'https://scandinaviangifts.com/donatello-clog/',
                    'https://scandinaviangifts.com/nyform-troll-n114/',
                    'https://scandinaviangifts.com/nyform-troll-n010/',
                    'https://scandinaviangifts.com/kosta-boda-contrast-bowl/',
                    'https://scandinaviangifts.com/orrefors-symbols-bowl/',
                    'https://scandinaviangifts.com/kosta-boda-pluto-candleholder/',
                    'https://scandinaviangifts.com/nyform-troll-n006/',
                    'https://scandinaviangifts.com/nyform-troll-n008/',
                    'https://scandinaviangifts.com/nyform-troll-n126/',
                    'https://scandinaviangifts.com/nyform-troll-n072/',
                    'https://scandinaviangifts.com/nyform-troll-n187/',
                    'https://scandinaviangifts.com/nyform-troll-n003/',
                    'https://scandinaviangifts.com/nyform-troll-n022/',
                    'https://scandinaviangifts.com/nyform-troll-n023/',
                    'https://scandinaviangifts.com/nyform-troll-n154/',
                    'https://scandinaviangifts.com/nyform-troll-n143/',
                    'https://scandinaviangifts.com/nyform-troll-n068/',
                    'https://scandinaviangifts.com/nyform-troll-n111/',
                    'https://scandinaviangifts.com/nyform-troll-n056/',
                    'https://scandinaviangifts.com/kosta-boda-contrast-bowl/',
                    'https://scandinaviangifts.com/orrefors-symbols-bowl/',
                    'https://scandinaviangifts.com/kosta-boda-pluto-candleholder/',
                    'https://scandinaviangifts.com/scandinavian-explorer-sport-bag/',
                    'https://scandinaviangifts.com/reindeer-antler-bar-accessories/',
                    'https://scandinaviangifts.com/kladdkaka-sticky-cake-pan/',
                    'https://scandinaviangifts.com/norway-flag-jersey/',
                    'https://scandinaviangifts.com/norway-flag-jersey-kids/',
                    'https://scandinaviangifts.com/almond-cake-pan/',
                    'https://scandinaviangifts.com/scandinavian-delights-raspberry-fruit-spread/',
                    'https://scandinaviangifts.com/scandinavian-delights-wild-blueberry-fruit-spread/',
                    'https://scandinaviangifts.com/scandinavian-delights-strawberry-fruit-spread/',
                    'https://scandinaviangifts.com/scandinavian-delights-boysenberry-fruit-spread/',
                    'https://scandinaviangifts.com/scandinavian-delights-lingonberry-fruit-spread/',
                    'https://scandinaviangifts.com/72-puffing-troll/',
                    'https://scandinaviangifts.com/83-the-4-vikingships/',
                    'https://scandinaviangifts.com/glimmi-reflector-vking-ship/',
                    'https://scandinaviangifts.com/glimmi-reflector-pippi-longstocking/',
                    'https://scandinaviangifts.com/glimmi-reflector-little-my/',
                    'https://scandinaviangifts.com/glimmi-reflector-angel/',
                    'https://scandinaviangifts.com/glimmi-reflector-dala/',
                    'https://scandinaviangifts.com/glimmi-reflector-moomin/',
                    'https://scandinaviangifts.com/glimmi-reflector-jolly-roger/',
                    'https://scandinaviangifts.com/glimmi-reflector-snowflake/',
                    'https://scandinaviangifts.com/glimmi-reflector-gnome/',
                    'https://scandinaviangifts.com/glimmi-reflector-swedish-flag/',
                    'https://scandinaviangifts.com/glimmi-reflector-warning-moose/',
                    'https://scandinaviangifts.com/glimmi-reflector-heart/',
                    'https://scandinaviangifts.com/glimmi-reflector-snowman/',
                    'https://scandinaviangifts.com/glimmi-reflector-moose/',
                    'https://scandinaviangifts.com/glimmi-reflector-gecko/',
                    'https://scandinaviangifts.com/glimmi-reflector-smiley/',
                    'https://scandinaviangifts.com/glimmi-reflector-knit/',
                    'https://scandinaviangifts.com/ice-lantern-starter-kit/',
                    'https://scandinaviangifts.com/ice-lantern-deluxe-kit/',
                    'https://scandinaviangifts.com/laila-deodorant/',
                    'https://scandinaviangifts.com/geir-deodorant-for-men/',
                    'https://scandinaviangifts.com/geir-for-men-3-4-oz-spray/',
                    'https://scandinaviangifts.com/laila-eau-de-parfum/',
                    'https://scandinaviangifts.com/hydrating-facial-mist/',
                    'https://scandinaviangifts.com/natural-moisture-repair/',
                    'https://scandinaviangifts.com/multi-action-eye-serum/',
                    'https://scandinaviangifts.com/luscious-lip-tingle/',
                    'https://scandinaviangifts.com/energizing-facial-cleanser/',
                    'https://scandinaviangifts.com/laila-body-wash/',
                    'https://scandinaviangifts.com/pewter-thors-hammer-necklace/',
                    'https://scandinaviangifts.com/runic-pendant-youth/',
                    'https://scandinaviangifts.com/runic-earrings-strength/',
                    'https://scandinaviangifts.com/runic-pendant-genuine/',
                    'https://scandinaviangifts.com/runic-pendant-grace/',
                    'https://scandinaviangifts.com/runic-earrings-love/',
                    'https://scandinaviangifts.com/runic-pendant-hope/',
                    'https://scandinaviangifts.com/runic-earrings-heart/',
                    'https://scandinaviangifts.com/runic-pendant-music/',
                    'https://scandinaviangifts.com/runic-earrings-luck/',
                    'https://scandinaviangifts.com/runic-earrings-energy/',
                    'https://scandinaviangifts.com/runic-pendant-creation/',
                    'https://scandinaviangifts.com/runic-pendant-energy/',
                    'https://scandinaviangifts.com/runic-pendant-heart/',
                    'https://scandinaviangifts.com/runic-pendant-strength/',
                    'https://scandinaviangifts.com/runic-pendant-wisdom/',
                    'https://scandinaviangifts.com/runic-pendant-luck/',
                    'https://scandinaviangifts.com/runic-pendant-love/',
                    'https://scandinaviangifts.com/en-gry-sif-big-bunny-basket/',
                    'https://scandinaviangifts.com/asp-holmblad-sterin-canal-taper-candles-20-pack/',
                    'https://scandinaviangifts.com/soap-beach-wavetree-london/',
                    'https://scandinaviangifts.com/soap-cosmopolitan-wavetree-london/',
                    'https://scandinaviangifts.com/soap-born-to-drive-wavetree-london/',
                    'https://scandinaviangifts.com/copy-of-felted-wool-flower-small/',
                    'https://scandinaviangifts.com/felted-wool-flower-large/',
                    'https://scandinaviangifts.com/danish-iron-3-cup-boat/',
                    'https://scandinaviangifts.com/flag-tiles/',
                    'https://scandinaviangifts.com/soap-beach-wavetree-london/',
                    'https://scandinaviangifts.com/soap-cosmopolitan-wavetree-london/',
                    'https://scandinaviangifts.com/soap-born-to-drive-wavetree-london/',
                    'https://scandinaviangifts.com/soap-lift/', 'https://scandinaviangifts.com/finnish-hand-cream/',
                    'https://scandinaviangifts.com/agg-tval-eggwhite-facial-soap/',
                    'https://scandinaviangifts.com/asp-holmblad-sterin-canal-taper-candles-20-pack/',
                    'https://scandinaviangifts.com/rotary-candleholder-bear-moose/',
                    'https://scandinaviangifts.com/rotary-candleholder-swallows/',
                    'https://scandinaviangifts.com/danish-papercut-mobile-nisse-in-window/',
                    'https://scandinaviangifts.com/danish-papercut-mobile-cat-in-window/',
                    'https://scandinaviangifts.com/rotary-candleholder-cats/',
                    'https://scandinaviangifts.com/rotary-candleholder-dogs/',
                    'https://scandinaviangifts.com/holiday-red-tealights/',
                    'https://scandinaviangifts.com/eco-clear-cup-tealights/',
                    'https://scandinaviangifts.com/advent-pillar-candle/',
                    'https://scandinaviangifts.com/ball-candles-white/',
                    'https://scandinaviangifts.com/swedish-wood-taper-holders/',
                    'https://scandinaviangifts.com/rotary-candleholder-trumpet-angels/',
                    'https://scandinaviangifts.com/swedish-dinner-tapers/',
                    'https://scandinaviangifts.com/clear-cup-tealights/',
                    'https://scandinaviangifts.com/rotary-candleholder-moose/',
                    'https://scandinaviangifts.com/swedish-chime-candles/',
                    'https://scandinaviangifts.com/kanalljus-channel-taper-candles/',
                    'https://scandinaviangifts.com/danish-iron-boat-candleholder/',
                    'https://scandinaviangifts.com/danish-iron-lantern-candleholder/',
                    'https://scandinaviangifts.com/danish-iron-low-tripod-arch/',
                    'https://scandinaviangifts.com/danish-iron-side-handle-holder/',
                    'https://scandinaviangifts.com/danish-iron-vase-holder/',
                    'https://scandinaviangifts.com/danish-iron-infinity-base-holder/',
                    'https://scandinaviangifts.com/danish-iron-tripod-taper-holder/',
                    'https://scandinaviangifts.com/iron-candleholder-4-tapers/',
                    'https://scandinaviangifts.com/danish-iron-two-cups-heart/',
                    'https://scandinaviangifts.com/ball-candles-white/',
                    'https://scandinaviangifts.com/danish-iron-crossed-tripod/',
                    'https://scandinaviangifts.com/danish-iron-waves-three-cup/',
                    'https://scandinaviangifts.com/danish-iron-4-heart-cup/',
                    'https://scandinaviangifts.com/danish-iron-curly-tripod-single/',
                    'https://scandinaviangifts.com/danish-iron-triple-heart/',
                    'https://scandinaviangifts.com/danish-iron-basic-single/',
                    'https://scandinaviangifts.com/danish-iron-coffee-cup/',
                    'https://scandinaviangifts.com/danish-iron-curly-bottom-taper-holder/',
                    'https://scandinaviangifts.com/sewn-nylon-flag-sweden/',
                    'https://scandinaviangifts.com/sewn-nylon-flag-norway/',
                    'https://scandinaviangifts.com/sewn-nylon-flag-finland/',
                    'https://scandinaviangifts.com/sewn-nylon-flag-denmark/',
                    'https://scandinaviangifts.com/sewn-nylon-flag-iceland/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-marit-grey-black/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-marit-blue-red/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-marit-black-red/',
                    'https://scandinaviangifts.com/swedish-mixed-rug-svea-red/',
                    'https://scandinaviangifts.com/swedish-mixed-rug-svea-blue/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-candy-green/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-happy-marine/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-happy-graphite/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-happy-grey/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-happy-blue/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-alfie-graphite/',
                    'https://scandinaviangifts.com/swedish-plastic-rug-alfie-blue/',
                    'https://scandinaviangifts.com/swedish-dishcloth-bunnies-in-the-grass/',
                    'https://scandinaviangifts.com/copy-of-felted-wool-flower-small/',
                    'https://scandinaviangifts.com/felted-wool-flower-large/',
                    'https://scandinaviangifts.com/potatoe-ricer-heavy-duty/',
                    'https://scandinaviangifts.com/nordqvist-best-moment-of-the-day-tea/',
                    'https://scandinaviangifts.com/nordic-vanilla-sugar/',
                    'https://scandinaviangifts.com/nordic-cinnamon-sugar/', 'https://scandinaviangifts.com/flag-tiles/',
                    'https://scandinaviangifts.com/kladdkaka-sticky-cake-pan/',
                    'https://scandinaviangifts.com/swedish-pearl-sugar/',
                    'https://scandinaviangifts.com/swedish-cakes-cookies/',
                    'https://scandinaviangifts.com/heart-shaped-tins/',
                    'https://scandinaviangifts.com/almond-cake-pan/',
                    'https://scandinaviangifts.com/lefse-turning-stick/',
                    'https://scandinaviangifts.com/finnish-cookbook/',
                    'https://scandinaviangifts.com/norwegian-cakes-cookies/',
                    'https://scandinaviangifts.com/knitware-spatulas/',
                    'https://scandinaviangifts.com/heritage-grill-silverstone/',
                    'https://scandinaviangifts.com/lefse-cozy-set/',
                    'https://scandinaviangifts.com/corrugated-rolling-pin/',
                    'https://scandinaviangifts.com/heritage-grill-satin/',
                    'https://scandinaviangifts.com/pastry-cloth-replacement/',
                    'https://scandinaviangifts.com/pastry-board-cloth-set/',
                    'https://scandinaviangifts.com/glass-almond-cake-platter/',
                    'https://scandinaviangifts.com/rim-cookie-cutter-set-1/',
                    'https://scandinaviangifts.com/gingerbread-cookie-cutter/',
                    'https://scandinaviangifts.com/engraved-rolling-pin/',
                    'https://scandinaviangifts.com/swedish-cookie-cutter-set/',
                    'https://scandinaviangifts.com/tomte-cookie-cutters/',
                    'https://scandinaviangifts.com/rim-cookie-cutter-set/',
                    'https://scandinaviangifts.com/pine-cone-tins/', 'https://scandinaviangifts.com/sandbakkel-tins/',
                    'https://scandinaviangifts.com/mug-lutefiskies/',
                    'https://scandinaviangifts.com/napkin-lilac-lunch/',
                    'https://scandinaviangifts.com/scandinavian-napkins-warm-things/',
                    'https://scandinaviangifts.com/scandinavian-napkins-holiday-trees/',
                    'https://scandinaviangifts.com/scandinavian-napkins-swedish-holiday/',
                    'https://scandinaviangifts.com/born-in-sweden-apple-candleholder/',
                    'https://scandinaviangifts.com/carl-larsson-paper-napkins/',
                    'https://scandinaviangifts.com/napkin-lilac-lunch/',
                    'https://scandinaviangifts.com/finnish-napkins-forest-tomte/',
                    'https://scandinaviangifts.com/fazer-marianne-chocolate/',
                    'https://scandinaviangifts.com/fazer-finnish-milk-chocolate/',
                    'https://scandinaviangifts.com/fazer-finnish-dark-chocolate/',
                    'https://scandinaviangifts.com/evergood-classic-coffee/',
                    'https://scandinaviangifts.com/milk-chocolate-licorice-balls/',
                    'https://scandinaviangifts.com/halva-finnish-licorice/',
                    'https://scandinaviangifts.com/fazer-dumle-finnish-candy/',
                    'https://scandinaviangifts.com/cloetta-kex-bar/',
                    'https://scandinaviangifts.com/nordic-sweets-bagged-swedish-treats/',
                    'https://scandinaviangifts.com/paulig-presidentti-finnish-coffee/',
                    'https://scandinaviangifts.com/paulig-juhla-mokka-finnish-coffee/',
                    'https://scandinaviangifts.com/insight-travel-guide-finland/',
                    'https://scandinaviangifts.com/insight-travel-guide-norway/',
                    'https://scandinaviangifts.com/2022-calendar-denmark/',
                    'https://scandinaviangifts.com/glimmi-reflector-swedish-flag/',
                    'https://scandinaviangifts.com/cloetta-mini-daim/',
                    'https://scandinaviangifts.com/milk-chocolate-toffee-sea-salt/',
                    'https://scandinaviangifts.com/norway-flag-jersey/',
                    'https://scandinaviangifts.com/milk-chocolate-toffee-sea-salt/',
                    'https://scandinaviangifts.com/sewn-nylon-flag-iceland/',
                    'https://scandinaviangifts.com/moomin-dishes/',
                    'https://scandinaviangifts.com/rock-snowflake-socks/',
                    'https://scandinaviangifts.com/ozone-floral-ribbons-socks/',
                    'https://scandinaviangifts.com/moomin-bibs/',
                    'https://scandinaviangifts.com/orrefors-delight-votive/',
                    'https://scandinaviangifts.com/nisse-drop-candles/',
                    'https://scandinaviangifts.com/ole-lena-jokes-book-2/',
                    'https://scandinaviangifts.com/ole-lena-jokes-book-1/',
                    'https://scandinaviangifts.com/moomins-and-the-great-flood/',
                    'https://scandinaviangifts.com/swedish-merino-wool-socks-bloom/',
                    'https://scandinaviangifts.com/swedish-merino-wool-socks-birgitta/',
                    'https://scandinaviangifts.com/ceramic-votive-cups/',
                    'https://scandinaviangifts.com/nisse-cone-candle/',
                    'https://scandinaviangifts.com/ceramic-tomte-taper-candleholder/',
                    'https://scandinaviangifts.com/folktale-ceramics/',
                    'https://scandinaviangifts.com/rosemaling-ceramic-mugs/',
                    'https://scandinaviangifts.com/midnight-sun-sterling-jewelry/',
                    'https://scandinaviangifts.com/by-the-fire-sami-folktales/',
                    'https://scandinaviangifts.com/glass-almond-cake-platter/',
                    'https://scandinaviangifts.com/swedish-fika/',
                    'https://scandinaviangifts.com/modern-scandinavian-baking/',
                    'https://scandinaviangifts.com/kladdkaka-sticky-cake-pan/',
                    'https://scandinaviangifts.com/danish-jul-notecards/',
                    'https://scandinaviangifts.com/almond-cake-pan/',
                    'https://scandinaviangifts.com/hafi-lingonberry-preserves/',
                    'https://scandinaviangifts.com/hafi-cloudberry-preserves/',
                    'https://scandinaviangifts.com/pine-cone-tins/', 'https://scandinaviangifts.com/sandbakkel-tins/',
                    'https://scandinaviangifts.com/scandinavian-napkins-swedish-holiday/',
                    'https://scandinaviangifts.com/swedish-dishcloth-christmas-icons/',
                    'https://scandinaviangifts.com/swedish-dishcloth-bl-joy/',
                    'https://scandinaviangifts.com/pepparkakor/',
                    'https://scandinaviangifts.com/rim-cookie-cutter-set-1/',
                    'https://scandinaviangifts.com/gingerbread-cookie-cutter/',
                    'https://scandinaviangifts.com/engraved-rolling-pin/',
                    'https://scandinaviangifts.com/tomte-cookie-cutters/',
                    'https://scandinaviangifts.com/rim-cookie-cutter-set/',
                    'https://scandinaviangifts.com/chocolate-covered-pepparkakor/',
                    'https://scandinaviangifts.com/lars-swedish-pepparkakor/',
                    'https://scandinaviangifts.com/fazer-marianne-chocolate/',
                    'https://scandinaviangifts.com/nordic-glogg-mulling-spice/',
                    'https://scandinaviangifts.com/fazer-finnish-milk-chocolate/',
                    'https://scandinaviangifts.com/fazer-finnish-dark-chocolate/',
                    'https://scandinaviangifts.com/milk-chocolate-licorice-balls/',
                    'https://scandinaviangifts.com/halva-finnish-licorice/',
                    'https://scandinaviangifts.com/skandikitchen-christmas/',
                    'https://scandinaviangifts.com/fazer-dumle-finnish-candy/',
                    'https://scandinaviangifts.com/nordic-sweets-bagged-swedish-treats/',
                    'https://scandinaviangifts.com/cloetta-mini-daim/',
                    'https://scandinaviangifts.com/milk-chocolate-toffee-sea-salt/',
                    'https://scandinaviangifts.com/freia-smil-chocolate-roll/',
                    'https://scandinaviangifts.com/daim-bar/', 'https://scandinaviangifts.com/marabou-milk-chocolate/',
                    'https://scandinaviangifts.com/melkesjokolade-bar/',
                    'https://scandinaviangifts.com/anthon-berg-marzipan-bar/',
                    'https://scandinaviangifts.com/swedish-losgodis-candy/',
                    'https://scandinaviangifts.com/scandinavian-napkins-holiday-trees/',
                    'https://scandinaviangifts.com/tipp-tapp/', 'https://scandinaviangifts.com/springtime-gnome-notes/',
                    'https://scandinaviangifts.com/the-little-springtime-book-of-gnomes/',
                    'https://scandinaviangifts.com/danish-skovnisser-notecards/',
                    'https://scandinaviangifts.com/lasercut-wood-tree/',
                    'https://scandinaviangifts.com/lasercut-wood-tree-ornament/',
                    'https://scandinaviangifts.com/wood-snowflake-ornament/',
                    'https://scandinaviangifts.com/glimmi-reflector-gnome/',
                    'https://scandinaviangifts.com/tomte-ribbon/', 'https://scandinaviangifts.com/finnish-tonttu/',
                    'https://scandinaviangifts.com/birdhouse-ornament/',
                    'https://scandinaviangifts.com/swedish-dishcloth-diamond-trees/',
                    'https://scandinaviangifts.com/swedish-dishcloth-tree-tomte/',
                    'https://scandinaviangifts.com/nordic-tomte-pocket-tissues/',
                    'https://scandinaviangifts.com/rotary-candleholder-white-pines/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-tomte-carrying-tree/',
                    'https://scandinaviangifts.com/swedish-tomte-victor-bjorn-or-benny/',
                    'https://scandinaviangifts.com/bearded-tomte-ornament/',
                    'https://scandinaviangifts.com/tomtar-ornaments-with-caps/',
                    'https://scandinaviangifts.com/tomte-boy-girl-ornaments/',
                    'https://scandinaviangifts.com/cone-tomte-ornament/',
                    'https://scandinaviangifts.com/swedish-tomte-figures/',
                    'https://scandinaviangifts.com/swedish-dishcloth-tall-tomte/',
                    'https://scandinaviangifts.com/felt-costumed-tomtar/',
                    'https://scandinaviangifts.com/tomtar-ornaments/',
                    'https://scandinaviangifts.com/swedish-dishcloth-merry-christmas/',
                    'https://scandinaviangifts.com/block-tomtar/',
                    'https://scandinaviangifts.com/finnish-napkins-forest-tomte/',
                    'https://scandinaviangifts.com/danish-papercut-mobile-nisse-in-window/',
                    'https://scandinaviangifts.com/danish-papercut-mobile-cat-in-window/',
                    'https://scandinaviangifts.com/rotary-candleholder-cats/',
                    'https://scandinaviangifts.com/rotary-candleholder-dogs/',
                    'https://scandinaviangifts.com/scandinavian-napkins-warm-things/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-cat-at-window/',
                    'https://scandinaviangifts.com/hundar/', 'https://scandinaviangifts.com/katter/',
                    'https://scandinaviangifts.com/swedish-dishcloth-forest-tomte/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-snowman-stuga/',
                    'https://scandinaviangifts.com/swedish-windshield-scraper/',
                    'https://scandinaviangifts.com/pewter-sleigh-ornament/',
                    'https://scandinaviangifts.com/swedish-dishcloth-snow-house/',
                    'https://scandinaviangifts.com/glimmi-reflector-snowflake/',
                    'https://scandinaviangifts.com/nyform-troll-n046/',
                    'https://scandinaviangifts.com/kosta-boda-mine-bowl/',
                    'https://scandinaviangifts.com/born-in-sweden-candleholder/',
                    'https://scandinaviangifts.com/simply-scandinavian/',
                    'https://scandinaviangifts.com/marimekko-pencil-set/',
                    'https://scandinaviangifts.com/marimekko-postcards/',
                    'https://scandinaviangifts.com/marimekko-birthday-book/',
                    'https://scandinaviangifts.com/swedish-birch-candleholder-black/',
                    'https://scandinaviangifts.com/bead-candle-napkin-rings-black/',
                    'https://scandinaviangifts.com/airy-090/', 'https://scandinaviangifts.com/hinza-tote/',
                    'https://scandinaviangifts.com/bead-candle-napkin-rings/',
                    'https://scandinaviangifts.com/swedish-wood-taper-holders/',
                    'https://scandinaviangifts.com/birdhouse-ornament/',
                    'https://scandinaviangifts.com/rotary-candleholder-swallows/',
                    'https://scandinaviangifts.com/swedish-dishcloth-birds-berries/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-blue-cap-birds/',
                    'https://scandinaviangifts.com/swedish-dishcloth-bird-feeder/',
                    'https://scandinaviangifts.com/swedish-dishcloth-lupine/',
                    'https://scandinaviangifts.com/hostnatur/', 'https://scandinaviangifts.com/varfaglar/',
                    'https://scandinaviangifts.com/born-in-sweden-bird-feeder/',
                    'https://scandinaviangifts.com/swedish-merino-wool-garden-socks/',
                    'https://scandinaviangifts.com/swedish-dishcloth-cardinal-pair/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-daisy-garden/',
                    'https://scandinaviangifts.com/swedish-dishcloth-chickadees/',
                    'https://scandinaviangifts.com/swedish-dishcloth-birds-on-wire/',
                    'https://scandinaviangifts.com/swedish-dishcloth-daisies/',
                    'https://scandinaviangifts.com/swedish-wooden-birds/', 'https://scandinaviangifts.com/selma/',
                    'https://scandinaviangifts.com/felt-polar-bear-ornament/',
                    'https://scandinaviangifts.com/felt-owl-ornament/',
                    'https://scandinaviangifts.com/rotary-candleholder-bear-moose/',
                    'https://scandinaviangifts.com/the-midsummer-tomte-the-little-rabbits/',
                    'https://scandinaviangifts.com/up-north-notecards/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-arctic-fox/',
                    'https://scandinaviangifts.com/swedish-dishcloth-christmas-window/',
                    'https://scandinaviangifts.com/laser-cut-board-utensils-fish/',
                    'https://scandinaviangifts.com/fox-felt-coin-purse/',
                    'https://scandinaviangifts.com/mushroom-ornament/',
                    'https://scandinaviangifts.com/mushroom-nutcracker/',
                    'https://scandinaviangifts.com/swedish-dishcloth-kh-rosehips/',
                    'https://scandinaviangifts.com/swedish-dishcloth-bear-fox/',
                    'https://scandinaviangifts.com/winter-notecards/',
                    'https://scandinaviangifts.com/swedish-dishcloth-fox-in-snow/',
                    'https://scandinaviangifts.com/swedish-merino-wool-reindeer-socks/',
                    'https://scandinaviangifts.com/birchwood-ornaments/',
                    'https://scandinaviangifts.com/swedish-dishcloth-oak-leaves/',
                    'https://scandinaviangifts.com/swedish-julienne-peeler/',
                    'https://scandinaviangifts.com/the-scandinavian-guide-to-happiness/',
                    'https://scandinaviangifts.com/swedish-dishcloth-dp-blueberry/',
                    'https://scandinaviangifts.com/swedish-dishcloth-cherries/',
                    'https://scandinaviangifts.com/tomater/', 'https://scandinaviangifts.com/kala-style-soaps/',
                    'https://scandinaviangifts.com/purus-bottle-brush/',
                    'https://scandinaviangifts.com/swedish-dishcloth-pomegranates/',
                    'https://scandinaviangifts.com/swedish-dishcloth-avocado/',
                    'https://scandinaviangifts.com/finnish-bio-cutting-board/',
                    'https://scandinaviangifts.com/animal-pot-guards/',
                    'https://scandinaviangifts.com/swedish-dish-brush/',
                    'https://scandinaviangifts.com/swedish-dishcloth-carrots-beets/',
                    'https://scandinaviangifts.com/swedish-dishcloth-blueberries/',
                    'https://scandinaviangifts.com/swedish-cloth-holders/',
                    'https://scandinaviangifts.com/swedish-drying-mat-blueberries/',
                    'https://scandinaviangifts.com/felt-viking-ornament/',
                    'https://scandinaviangifts.com/the-nordic-book-of-runes/',
                    'https://scandinaviangifts.com/norse-mythology-for-kids/',
                    'https://scandinaviangifts.com/the-viking-hondbok/',
                    'https://scandinaviangifts.com/nordic-love-jigsaw-puzzle/',
                    'https://scandinaviangifts.com/viking-finds-notecards/',
                    'https://scandinaviangifts.com/glimmi-reflector-vking-ship/',
                    'https://scandinaviangifts.com/laser-cut-board-spreader-1/',
                    'https://scandinaviangifts.com/moomins-hide-seek/',
                    'https://scandinaviangifts.com/viking-ship-ornament-pewter/',
                    'https://scandinaviangifts.com/runic-earrings-love/',
                    'https://scandinaviangifts.com/viking-ornaments-sweden/',
                    'https://scandinaviangifts.com/norwegian-pewter-viking-ship-prow/',
                    'https://scandinaviangifts.com/pewter-thors-hammer-necklace/',
                    'https://scandinaviangifts.com/runic-pendant-love/',
                    'https://scandinaviangifts.com/viking-jewelry/', 'https://scandinaviangifts.com/orrefors-wave-set/',
                    'https://scandinaviangifts.com/dala-horse-felt-purse/',
                    'https://scandinaviangifts.com/scandikitchen-the-essence-of-hygge/',
                    'https://scandinaviangifts.com/swedish-dishcloth-multi-hearts/',
                    'https://scandinaviangifts.com/lovskog/', 'https://scandinaviangifts.com/orrefors-heart-bowl/',
                    'https://scandinaviangifts.com/glimmi-reflector-dala/',
                    'https://scandinaviangifts.com/dala-horse-ornaments/',
                    'https://scandinaviangifts.com/swedish-dishcloth-dala-horses/',
                    'https://scandinaviangifts.com/wooden-heart-ornament/',
                    'https://scandinaviangifts.com/kurbitsblom/',
                    'https://scandinaviangifts.com/finnish-burlwood-heart-necklace/',
                    'https://scandinaviangifts.com/rock-snowflake-socks/',
                    'https://scandinaviangifts.com/ozone-floral-ribbons-socks/',
                    'https://scandinaviangifts.com/swedish-merino-wool-socks-bloom/',
                    'https://scandinaviangifts.com/swedish-merino-wool-socks-birgitta/',
                    'https://scandinaviangifts.com/nils-daulaire/', 'https://scandinaviangifts.com/marius-redblue/',
                    'https://scandinaviangifts.com/merino-wool-cap-scarf/',
                    'https://scandinaviangifts.com/nordic-knit-hat/',
                    'https://scandinaviangifts.com/knitware-spatulas/',
                    'https://scandinaviangifts.com/folktale-ceramics/',
                    'https://scandinaviangifts.com/rosemaling-ceramic-mugs/',
                    'https://scandinaviangifts.com/midnight-sun-sterling-jewelry/',
                    'https://scandinaviangifts.com/by-the-fire-sami-folktales/',
                    'https://scandinaviangifts.com/swedish-dishcloth-dp-rosemaling/',
                    'https://scandinaviangifts.com/buff-rosemaling-multifunctional-headwear-mask/',
                    'https://scandinaviangifts.com/norwegian-sterling-solje/',
                    'https://scandinaviangifts.com/suzanne-toftey-wool-scarf/',
                    'https://scandinaviangifts.com/pewter-stocking-ornament/',
                    'https://scandinaviangifts.com/nyform-troll-n023/',
                    'https://scandinaviangifts.com/pewter-stav-church-ornament/',
                    'https://scandinaviangifts.com/pewter-mittens-ornament/',
                    'https://scandinaviangifts.com/norwegian-pewter-stabbur-ornament/',
                    'https://scandinaviangifts.com/pewter-rosemaling-tinne-ornament/',
                    'https://scandinaviangifts.com/pewter-heart-ornament/',
                    'https://scandinaviangifts.com/moomin-dishes/', 'https://scandinaviangifts.com/moomin-bibs/',
                    'https://scandinaviangifts.com/ole-lena-jokes-book-2/',
                    'https://scandinaviangifts.com/ole-lena-jokes-book-1/',
                    'https://scandinaviangifts.com/moomins-and-the-great-flood/',
                    'https://scandinaviangifts.com/for-the-love-of-cod/',
                    'https://scandinaviangifts.com/uffda-lip-balm/',
                    'https://scandinaviangifts.com/swedish-windshield-scraper/',
                    'https://scandinaviangifts.com/2022-calendar-denmark/',
                    'https://scandinaviangifts.com/pewter-uffda-ornament/',
                    'https://scandinaviangifts.com/2022-calendar-finland/',
                    'https://scandinaviangifts.com/ole-lenas-scandinavian-fortune-cookies/',
                    'https://scandinaviangifts.com/ceramic-votive-cups/',
                    'https://scandinaviangifts.com/nisse-cone-candle/',
                    'https://scandinaviangifts.com/ceramic-tomte-taper-candleholder/',
                    'https://scandinaviangifts.com/bead-candle-napkin-rings-black/',
                    'https://scandinaviangifts.com/stugan/', 'https://scandinaviangifts.com/tomten/',
                    'https://scandinaviangifts.com/born-in-sweden-apple-candleholder/',
                    'https://scandinaviangifts.com/advent-pillar-candle/',
                    'https://scandinaviangifts.com/glass-outdoor-votive/',
                    'https://scandinaviangifts.com/bead-candle-napkin-rings/',
                    'https://scandinaviangifts.com/swedish-birch-candleholder/',
                    'https://scandinaviangifts.com/orrefors-delight-votive/',
                    'https://scandinaviangifts.com/danish-iron-low-tripod-arch/',
                    'https://scandinaviangifts.com/orrefors-ice-cube-votive/',
                    'https://scandinaviangifts.com/holiday-red-tealights/',
                    'https://scandinaviangifts.com/eco-clear-cup-tealights/',
                    'https://scandinaviangifts.com/lingonberry-candlering/',
                    'https://scandinaviangifts.com/ball-candles-white/',
                    'https://scandinaviangifts.com/orrefors-amour-votive/',
                    'https://scandinaviangifts.com/orrefors-discus-votive/',
                    'https://scandinaviangifts.com/swedish-dinner-tapers/',
                    'https://scandinaviangifts.com/swedish-chime-candles/',
                    'https://scandinaviangifts.com/kanalljus-channel-taper-candles/',
                    'https://scandinaviangifts.com/6-hour-tealights/',
                    'https://scandinaviangifts.com/danish-iron-curly-bottom-taper-holder/',
                    'https://scandinaviangifts.com/ball-candle-champagne/',
                    'https://scandinaviangifts.com/danish-iron-double-curls/',
                    'https://scandinaviangifts.com/ball-candles-blue/',
                    'https://scandinaviangifts.com/ball-candles-cinnamon-red/',
                    'https://scandinaviangifts.com/nisse-drop-candles/', 'https://scandinaviangifts.com/julgran/',
                    'https://scandinaviangifts.com/nisse-taper-candles/',
                    'https://scandinaviangifts.com/moomin-sock-pink-stripe/'])
          )
