import random
import unittest
from time import sleep

from selenium import webdriver
from selenium.webdriver import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from frontend.Testing.Unit_Test.Unit_Test_Login import chrome_options


class TestWhlistList(unittest.TestCase):
    def setUp(self):
        # self.driver = webdriver.Chrome(options=chrome_options)  # 不显示浏览器，静默模式
        self.driver = webdriver.Chrome()
        self.driver.get("http://localhost:3000/wish/wishForm")
        if self.driver.current_url == "http://localhost:3000/login":
            self.driver.find_element_by_xpath('//*[@id="email"]').clear()
            self.driver.find_element_by_xpath('//*[@id="email"]').send_keys("111@qq.com")
            self.driver.find_element_by_xpath('//*[@id="password"]').clear()
            self.driver.find_element_by_xpath('//*[@id="password"]').send_keys("1234")
            self.driver.find_element_by_xpath('//*[@id="root"]/main/div/form/button').click()
            sleep(5)

    # self.driver.implicitly_wait(10)

    def normal(self):
        """Can generated normal wlishlist"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test two")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def nick_name_is_English_text(self):
        """Can generated normal wlishlist nick_name_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test two")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def nick_name_is_null(self):
        """Can't generated normal wlishlist nick_name_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def nick_name_Special_characters(self):
        """Can generated normal wlishlist  nick_name_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("$@#$%!#@!$")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def nick_name_Combining_characters(self):
        """Can generated normal wlishlist nick_name_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("$#!21331fasfasc")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def first_name_is_English_text(self):
        """Can generated normal wlishlist first_name_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test two")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def nfirst_name_is_null(self):
        """Can't generated normal wlishlist first_name_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 2")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def first_name_Special_characters(self):
        """Can't generated normal wlishlist  first_name_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 3")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("#!#@!3!@31")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def first_name_Combining_characters(self):
        """Can't generated normal wlishlist first_name_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 4")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("$@#$@3243")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def last_name_is_English_text(self):
        """Can generated normal wlishlist last_name_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 5")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def last_name_is_null(self):
        """Can't generated normal wlishlist last_name_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 6")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def last_name_Special_characters(self):
        """Can't generated normal wlishlist  last_name_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 7")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("$#@$@#$@")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def last_name_Combining_characters(self):
        """Can't generated normal wlishlist last_name_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 10")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("FDSF442342")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def description_is_English_text(self):
        """Can generated normal wlishlist description_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 8")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def description_is_null(self):
        """Can generated normal wlishlist description_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 9")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def description_Special_characters(self):
        """Can generated normal wlishlist  description_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 11")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("%@%$^%$$@#%@#")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def description_Combining_characters(self):
        """Can generated normal wlishlist description_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 13")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("$@#$@#$@FSfdsFSWERT$#%#$@$%@#$#@%%32523423")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def street_is_English_text(self):
        """Can generated normal wlishlist street_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 14")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish")  # 预期测试结果
        sleep(1)

    def street_name_is_null(self):
        """Can't generated normal wlishlist street_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys(" test 15")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def street_Special_characters(self):
        """Can't generated normal wlishlist  street_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 16")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("%#@$@#$@#$#@%@$@3")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def street_Combining_characters(self):
        """Can't generated normal wlishlist street_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 16")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("$@#$@#fsdfsdfs54352")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def phone_is_English_text(self):
        """Can't generated normal wlishlist phone_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 17")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("aaaaaaaaaaaaaaaaaaaaa")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def phone_is_null(self):
        """Can't generated normal wlishlist phone_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 18")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def phone_Special_characters(self):
        """Can't generated normal wlishlist  phone_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 19")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("$#@$#@@#!")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def phone_Combining_characters(self):
        """Can't generated normal wlishlist phone_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 28")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("$@#@#ewfs3242")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def postcode_is_English_text(self):
        """Can't generated normal wlishlist postcode_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 21")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("testee")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def postcode_is_null(self):
        """Can't generated normal wlishlist postcode_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 22")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def postcode_Special_characters(self):
        """Can't generated normal wlishlist  postcode_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 29")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("@$@$@#$@#@$")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def postcode_Combining_characters(self):
        """Can't generated normal wlishlist postcode_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 24")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("afas#$@$324")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def time_is_English_text(self):
        """Can't generated normal wlishlist time_is_English_text"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 25")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("sdfsfs")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def time_is_null(self):
        """Can't generated normal wlishlist time_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def time_Special_characters(self):
        """Can't generated normal wlishlist  time_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 26")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("$@##$%$@%@$2")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def time_Combining_characters(self):
        """Can't generated normal wlishlist time_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("test 27")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("Australia")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("faf$#@$@werw")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def country_is_null(self):
        """Can't generated normal wlishlist country_is_null"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def country_Special_characters(self):
        """Can't generated normal wlishlist  country_Special_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("$@#$%!#@!$")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("$##!#!!@")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)

    def country_Combining_characters(self):
        """Can't generated normal wlishlist country_Combining_characters"""
        driver = self.driver
        driver.find_element_by_xpath('//*[@id="titleP"]').clear()
        driver.find_element_by_xpath('//*[@id="titleP"]').send_keys("$#!21331fasfasc")
        driver.find_element_by_xpath('//*[@id="firstP"]').clear()
        driver.find_element_by_xpath('//*[@id="firstP"]').send_keys("reni")
        driver.find_element_by_xpath('//*[@id="lastP"]').clear()
        driver.find_element_by_xpath('//*[@id="lastP"]').send_keys("niei")
        driver.find_element_by_xpath('//*[@id="desprops"]').clear()
        driver.find_element_by_xpath('//*[@id="desprops"]').send_keys("this wlishlist is for test")
        driver.find_element_by_xpath('//*[@id="country"]').clear()
        selectCountry = driver.find_element_by_xpath('//*[@id="country"]')
        selectCountry.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="country"]').send_keys("$#@@#dsssad")
        driver.find_element_by_xpath('//*[@id="country"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').clear()
        selectAddress = driver.find_element_by_xpath('//*[@id="combo-box-demo"]')
        selectAddress.click()
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys("New South Wales")
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.DOWN)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="combo-box-demo"]').send_keys(Keys.ENTER)
        sleep(2)
        driver.find_element_by_xpath('//*[@id="adderss"]').clear()
        driver.find_element_by_xpath('//*[@id="adderss"]').send_keys("noemwr test dsop")
        driver.find_element_by_xpath('//*[@id="phone"]').clear()
        driver.find_element_by_xpath('//*[@id="phone"]').send_keys("12222112133")
        driver.find_element_by_xpath('//*[@id="postcode"]').clear()
        driver.find_element_by_xpath('//*[@id="postcode"]').send_keys("518993")
        driver.find_element_by_xpath('//*[@id="time"]').click()
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.CONTROL,"a")
        driver.find_element_by_xpath('//*[@id="time"]').send_keys(Keys.DELETE)
        driver.find_element_by_xpath('//*[@id="time"]').send_keys("06192022")
        driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/form/div[5]/button').click()
        sleep(10)
        curr_url = driver.current_url
        self.assertEqual(curr_url, "http://localhost:3000/wish/wishForm")  # 预期测试结果
        sleep(1)



    def tearDown(self):
        self.driver.quit()

if __name__ == '__main__':
    # print()
    print(list(set(dir(TestWhlistList)) ^ set(dir(unittest.TestCase))))